### ISSUE TITLE
Class "Url\Seo" not found

### ISSUE THREAD

**Issue by iceman-fx** [alexplusde/yrewrite_metainfo#15]
Wenn ich nach Anleitung vorgehe und im Header mittels
`<?= domain::getHead() ?>`
mir die Werte ausgeben lassen will, dann bekomme ich einen Ooops.

23.07.2024, 13:08:11Error | Class "Url\Seo" not foundDatei: redaxo/src/addons/yrewrite_metainfo/fragments/yrewrite_metainfo/head.php:8

**Comment by skerbis** [comment]
Keine Prüfung hier: https://github.com/alexplusde/yrewrite_metainfo/blob/8cb9ab9133d73cd065b1e42b5707b692d0b29f9d/fragments/yrewrite_metainfo/head.php#L6
